import { useCallback, useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { CalendarDays, Check, ChevronRight, Clock3, LogOut, Pause, Play, Plus, Power, Scissors, Trash2, X } from 'lucide-react';
import { isSupabaseConfigured, SETTINGS_ID, supabase } from '../lib/supabase';

const initialSettings={booking_enabled:true,shop_open:true,paused_until:null};
const formatTime=t=>new Date(`2000-01-01T${t}`).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'});
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const statusLabels={pending:'Pending',confirmed:'Confirmed',completed:'Completed',cancelled:'Cancelled',no_show:'No show'};
const whatsappPhone=value=>{const digits=String(value||'').replace(/\D/g,'');if(digits.startsWith('91')&&digits.length===12)return digits;if(digits.length===10)return `91${digits}`;return digits.replace(/^0+/,'')};
const whatsappMessage=(booking,status)=>{const date=new Date(`${booking.appointment_date}T00:00`).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'});if(status==='confirmed')return `Hello ${booking.customer_name}, your appointment at I Cut Hair Grooming Studio is confirmed for ${date} at ${formatTime(booking.appointment_time)} for ${booking.service}. We look forward to seeing you.`;return `Hello ${booking.customer_name}, your appointment at I Cut Hair Grooming Studio for ${date} at ${formatTime(booking.appointment_time)} has been cancelled. Please contact us if you would like to choose another time.`};
const whatsappUrl=(booking,status)=>`https://wa.me/${whatsappPhone(booking.customer_phone)}?text=${encodeURIComponent(whatsappMessage(booking,status))}`;

function Toast({message}){return <AnimatePresence>{message&&<motion.div className="owner-toast" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}}><Check/>{message}</motion.div>}</AnimatePresence>}
function SetupRequired(){return <main className="owner-shell owner-center"><div className="owner-auth-card"><div className="owner-mark">IC</div><h1>Connect the secure database</h1><p>Add <code>VITE_SUPABASE_URL</code> and <code>VITE_SUPABASE_ANON_KEY</code> to Vercel, then run <code>supabase/schema.sql</code> in your Supabase project.</p><a href="/">Return to website</a></div></main>}

function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setError(error.message);setBusy(false)};return <main className="owner-shell owner-center"><motion.form className="owner-auth-card" onSubmit={submit} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="owner-mark">IC</div><span className="owner-kicker">PRIVATE ACCESS</span><h1>Owner sign in</h1><p>Manage availability and appointments securely.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="owner-error">{error}</div>}<button className="owner-primary" disabled={busy}>{busy?'Signing in…':'Sign in'}<ChevronRight/></button><a href="/">Back to customer website</a></motion.form></main>}

function Dashboard({session}){
 const[settings,setSettings]=useState(initialSettings),[bookings,setBookings]=useState([]),[blocks,setBlocks]=useState([]),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[toast,setToast]=useState(''),[now,setNow]=useState(Date.now()),[blockOpen,setBlockOpen]=useState(false);
 const[notificationPermission,setNotificationPermission]=useState(()=>typeof Notification==='undefined'?'unsupported':Notification.permission);
 const notify=msg=>{setToast(msg);setTimeout(()=>setToast(''),2600)};
 const load=useCallback(async()=>{const[{data:s},{data:b},{data:bt},{data:p}]=await Promise.all([supabase.from('shop_settings').select('*').eq('id',SETTINGS_ID).single(),supabase.from('bookings').select('*').order('appointment_date').order('appointment_time'),supabase.from('blocked_times').select('*').gte('date',localDate()).order('date').order('start_time'),supabase.from('profiles').select('*').eq('id',session.user.id).single()]);if(!p||p.role!=='owner'){await supabase.auth.signOut();return}setProfile(p);if(s)setSettings(s);setBookings(b||[]);setBlocks(bt||[]);setLoading(false)},[session.user.id]);
 useEffect(()=>{load();const channel=supabase.channel('owner-live').on('postgres_changes',{event:'*',schema:'public',table:'shop_settings'},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'bookings'},payload=>{load();const booking=payload.new;notify(`New booking from ${booking.customer_name}`);if(typeof Notification!=='undefined'&&Notification.permission==='granted')new Notification('New I Cut booking',{body:`${booking.customer_name} · ${booking.service} · ${formatTime(booking.appointment_time)}`,icon:'/favicon.ico',tag:`booking-${booking.id}`})}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'bookings'},load).on('postgres_changes',{event:'DELETE',schema:'public',table:'bookings'},load).on('postgres_changes',{event:'*',schema:'public',table:'blocked_times'},load).subscribe();const tick=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(tick);supabase.removeChannel(channel)}},[load]);
 const paused=settings&&!settings.booking_enabled&&(settings.paused_until===null||new Date(settings.paused_until).getTime()>now); const remaining=paused&&settings.paused_until?Math.max(0,new Date(settings.paused_until)-now):null;
 useEffect(()=>{if(settings.paused_until&&new Date(settings.paused_until).getTime()<=now&&!settings.booking_enabled){supabase.from('shop_settings').update({booking_enabled:true,paused_until:null,updated_at:new Date().toISOString()}).eq('id',SETTINGS_ID).then(load)}},[now,settings,load]);
 const updateSettings=async changes=>{const{error}=await supabase.from('shop_settings').update({...changes,updated_at:new Date().toISOString()}).eq('id',SETTINGS_ID);if(error)notify(error.message);else{setSettings(v=>({...v,...changes}));notify('Settings updated')}};
 const enableNotifications=()=>{if(typeof Notification==='undefined'){notify('Notifications are not supported on this browser');return}window.OneSignalDeferred=window.OneSignalDeferred||[];window.OneSignalDeferred.push(async OneSignal=>{await OneSignal.Notifications.requestPermission();const permission=Notification.permission;setNotificationPermission(permission);notify(permission==='granted'?'Push notifications enabled':'Notification permission was not allowed')})};
 const pauseFor=minutes=>updateSettings({booking_enabled:false,paused_until:minutes?new Date(Date.now()+minutes*60000).toISOString():null});
 const changeStatus=async(booking,status)=>{if(status==='completed'&&!confirm('Mark this appointment as completed?'))return false;const{error}=await supabase.from('bookings').update({status}).eq('id',booking.id);if(error){notify(error.message);return false}setBookings(v=>v.map(b=>b.id===booking.id?{...b,status}:b));notify(`Marked ${statusLabels[status].toLowerCase()}`);return true};
 const addBlock=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from('blocked_times').insert({date:f.get('date'),start_time:f.get('start'),end_time:f.get('end'),reason:f.get('reason').trim()||null});if(error)notify(error.message);else{setBlockOpen(false);notify('Time blocked');load()}};
 const deleteBlock=async id=>{const{error}=await supabase.from('blocked_times').delete().eq('id',id);if(!error){setBlocks(v=>v.filter(b=>b.id!==id));notify('Block removed')}};
 const today=localDate(),todays=bookings.filter(b=>b.appointment_date===today&&!['cancelled'].includes(b.status)),upcoming=bookings.filter(b=>b.appointment_date>today&&!['cancelled'].includes(b.status));
 const groups=useMemo(()=>upcoming.reduce((a,b)=>{(a[b.appointment_date]??=[]).push(b);return a},{}),[upcoming]);
 if(loading)return <main className="owner-shell owner-center"><div className="owner-loader"/></main>;
 return <main className="owner-shell"><header className="owner-header"><div><div className="owner-brand">I CUT <span>OWNER DASHBOARD</span></div><small>{profile?.email}</small></div><button onClick={()=>supabase.auth.signOut()} aria-label="Sign out"><LogOut/></button></header><div className="owner-content">
  {notificationPermission!=='granted'&&<section className="owner-alert-card"><div><span className="owner-kicker">NEW BOOKING ALERTS</span><h2>Never miss a booking</h2><p>Allow notifications to receive an alert when a customer books.</p></div><button onClick={enableNotifications} disabled={notificationPermission==='unsupported'}>Enable notifications</button></section>}
  <section className={`owner-status ${settings.shop_open?'is-open':'is-closed'}`}><div><span className="owner-kicker">SHOP STATUS</span><h1><i/>{settings.shop_open?'OPEN':'CLOSED'}</h1><p>{settings.shop_open?'Customers can see the booking availability.':'All new booking requests are disabled.'}</p></div><button className="owner-switch" aria-pressed={settings.shop_open} onClick={()=>updateSettings({shop_open:!settings.shop_open})}><span/></button></section>
  <section className={`owner-booking-state ${paused?'is-paused':''}`}><div className="owner-state-icon">{paused?<Pause/>:<Play/>}</div><span className="owner-kicker">BOOKING STATUS</span><h2>{paused?'Bookings paused':'Accepting bookings'}</h2>{remaining!==null&&<p>Automatically reopening in <strong>{Math.floor(remaining/60000)}:{String(Math.floor((remaining%60000)/1000)).padStart(2,'0')}</strong></p>}<button className={paused?'owner-primary resume':'owner-primary danger'} onClick={()=>paused?updateSettings({booking_enabled:true,paused_until:null}):pauseFor(null)}>{paused?<><Play/>Resume bookings</>:<><Pause/>Pause bookings</>}</button></section>
  <section className="owner-card"><div className="owner-section-title"><div><span className="owner-kicker">QUICK CONTROL</span><h2>Pause bookings for</h2></div><Clock3/></div><div className="pause-grid">{[[15,'15 MIN'],[30,'30 MIN'],[45,'45 MIN'],[60,'1 HOUR']].map(([m,l])=><button key={m} onClick={()=>pauseFor(m)}>{l}</button>)}</div><div className="custom-pause"><input id="custom-minutes" type="number" min="1" max="1440" placeholder="Minutes"/><button onClick={()=>{const n=Number(document.getElementById('custom-minutes').value);if(n>0)pauseFor(n)}}>Custom time</button><button onClick={()=>pauseFor(null)}>Until I resume</button></div></section>
  <section className="owner-card"><div className="owner-section-title"><div><span className="owner-kicker">AVAILABILITY</span><h2>Blocked times</h2></div><button className="owner-add" onClick={()=>setBlockOpen(!blockOpen)}><Plus/>Add</button></div><AnimatePresence>{blockOpen&&<motion.form className="block-form" onSubmit={addBlock} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><label>Date<input name="date" type="date" min={today} required/></label><div><label>From<input name="start" type="time" required/></label><label>To<input name="end" type="time" required/></label></div><label>Reason<input name="reason" maxLength="100" placeholder="e.g. Lunch break"/></label><button className="owner-primary"><Plus/>Block time</button></motion.form>}</AnimatePresence><div className="block-list">{blocks.length?blocks.map(b=><div key={b.id}><CalendarDays/><span><b>{new Date(`${b.date}T00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short'})} · {formatTime(b.start_time)}–{formatTime(b.end_time)}</b><small>{b.reason||'Unavailable'}</small></span><button onClick={()=>deleteBlock(b.id)} aria-label="Delete blocked time"><Trash2/></button></div>):<p className="owner-empty">No upcoming blocked times.</p>}</div></section>
  <Appointments title="Today’s appointments" subtitle={`${todays.length} scheduled`} items={todays} onStatus={changeStatus}/>
  <section className="owner-card"><div className="owner-section-title"><div><span className="owner-kicker">COMING UP</span><h2>Upcoming bookings</h2></div></div>{Object.keys(groups).length?Object.entries(groups).map(([date,items])=><div className="upcoming-group" key={date}><h3>{new Date(`${date}T00:00`).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</h3>{items.map(b=><BookingRow key={b.id} booking={b} onStatus={changeStatus}/>)}</div>):<p className="owner-empty">No upcoming bookings.</p>}</section>
 </div><Toast message={toast}/></main>
}
function Appointments({title,subtitle,items,onStatus}){return <section className="owner-card"><div className="owner-section-title"><div><span className="owner-kicker">TODAY</span><h2>{title}</h2><small>{subtitle}</small></div><Scissors/></div>{items.length?items.map(b=><BookingRow key={b.id} booking={b} onStatus={onStatus}/>):<p className="owner-empty">No appointments scheduled today.</p>}</section>}
function BookingRow({booking:b,onStatus}){const sendAndUpdate=(e,status)=>{if(status==='cancelled'&&!confirm('Cancel this appointment and open the WhatsApp cancellation message?')){e.preventDefault();return}onStatus(b,status)};return <article className="booking-row"><div className="booking-time">{formatTime(b.appointment_time)}</div><div className="booking-info"><h3>{b.customer_name}</h3><p>{b.service} · <a href={`tel:${b.customer_phone}`}>{b.customer_phone}</a></p><span className={`booking-badge ${b.status}`}>{statusLabels[b.status]}</span></div><div className="booking-actions">{b.status==='pending'&&<a href={whatsappUrl(b,'confirmed')} target="_blank" rel="noreferrer" onClick={e=>sendAndUpdate(e,'confirmed')}>Confirm &amp; open WhatsApp</a>}{b.status==='confirmed'&&<a href={whatsappUrl(b,'confirmed')} target="_blank" rel="noreferrer">Send WhatsApp confirmation</a>}{!['completed','cancelled','no_show'].includes(b.status)&&<button onClick={()=>onStatus(b,'completed')}>Complete</button>}{!['cancelled','completed'].includes(b.status)&&<button onClick={()=>onStatus(b,'no_show')}>No show</button>}{!['cancelled','completed'].includes(b.status)&&<a className="cancel" href={whatsappUrl(b,'cancelled')} target="_blank" rel="noreferrer" onClick={e=>sendAndUpdate(e,'cancelled')}>Cancel &amp; open WhatsApp</a>}</div></article>}

export default function OwnerApp(){const[session,setSession]=useState(undefined);useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);if(!isSupabaseConfigured)return <SetupRequired/>;if(session===undefined)return <main className="owner-shell owner-center"><div className="owner-loader"/></main>;return session?<Dashboard session={session}/>:<Login/>}
