import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, Check, Clock3, MessageCircle } from 'lucide-react';
import { business, services } from '../data';
import { isSupabaseConfigured, SETTINGS_ID, supabase } from '../lib/supabase';

const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.65}};
const today=()=>new Date().toISOString().split('T')[0];
const errorsByCode={SHOP_CLOSED:'The studio is currently closed.',BOOKINGS_PAUSED:'Bookings are temporarily paused.',TIME_BLOCKED:'That time is unavailable. Please choose another time.',SLOT_TAKEN:'That appointment was just booked. Please choose another time.',PAST_DATE:'Please choose today or a future date.'};

export default function CustomerBooking(){
 const[settings,setSettings]=useState(null),[busy,setBusy]=useState(false),[errors,setErrors]=useState({}),[success,setSuccess]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{if(!supabase)return;const load=()=>supabase.from('shop_settings').select('*').eq('id',SETTINGS_ID).single().then(({data})=>setSettings(data));load();const channel=supabase.channel('public-booking-status').on('postgres_changes',{event:'UPDATE',schema:'public',table:'shop_settings'},({new:v})=>setSettings(v)).subscribe();const timer=setInterval(()=>setNow(Date.now()),30000);return()=>{clearInterval(timer);supabase.removeChannel(channel)}},[]);
 const paused=settings&&!settings.booking_enabled&&(!settings.paused_until||new Date(settings.paused_until).getTime()>now);const closed=settings&&!settings.shop_open;
 const submit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),required=['name','phone','service','date','time'],next={};required.forEach(k=>{if(!f.get(k)?.trim())next[k]='This field is required.'});if(f.get('date')&&f.get('date')<today())next.date='Please choose today or a future date.';setErrors(next);if(Object.keys(next).length)return;
  if(!isSupabaseConfigured){const msg=`Hello I Cut Hair Grooming Studio, I would like to request an appointment.\n\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nService: ${f.get('service')}\nPreferred date: ${f.get('date')}\nPreferred time: ${f.get('time')}\nMessage: ${f.get('message')||'—'}`;location.href=`${business.whatsappBase}?text=${encodeURIComponent(msg)}`;return}
  setBusy(true);setSuccess(false);const booking={name:String(f.get('name')),service:String(f.get('service')),date:String(f.get('date')),time:String(f.get('time'))};const{error}=await supabase.rpc('create_booking',{p_customer_name:f.get('name'),p_customer_phone:f.get('phone'),p_service:f.get('service'),p_appointment_date:f.get('date'),p_appointment_time:f.get('time'),p_message:f.get('message')||null});setBusy(false);if(error){const code=Object.keys(errorsByCode).find(k=>error.message.includes(k));setErrors({form:errorsByCode[code]||'We could not submit your request. Please try again.'})}else{fetch('/api/notify-owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(booking)}).catch(()=>{});form.reset();setSuccess(true)}};
 const field=(name,label,type='text')=><label>{label}<input name={name} type={type} min={type==='date'?today():undefined} aria-invalid={!!errors[name]}/>{errors[name]&&<small>{errors[name]}</small>}</label>;
 const reopens=paused&&settings.paused_until?new Date(settings.paused_until).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}):null;
 return <section id="appointment" className="section appointment"><div className="wrap appointment-layout"><div><div className="section-head"><span className="eyebrow">REQUEST A VISIT</span><h2>Your Next Look Starts Here</h2><p>Share your preferred service and time. The studio will review your appointment request.</p></div><div className="appointment-note whatsapp-update"><MessageCircle/><p><b>WhatsApp updates</b><br/>You will receive your booking updates on WhatsApp.</p></div></div>
  {(closed||paused)?<motion.div {...reveal} className="booking-unavailable"><Clock3/><span className="eyebrow">CURRENTLY UNAVAILABLE</span><h3>{closed?'I Cut is currently closed':'Bookings are temporarily paused'}</h3><p>{closed?'Booking will be available again when the shop reopens.':reopens?`Booking will reopen at ${reopens}.`:'Please check again shortly.'}</p><a className="button outline" href={business.callUrl}>Call the studio</a></motion.div>:
  success?<motion.div {...reveal} className="booking-success" role="status" aria-live="polite"><span className="success-icon"><Check/></span><span className="eyebrow">REQUEST RECEIVED</span><h3>Your booking has been submitted.</h3><p>Your appointment request was received successfully. You will receive confirmation and booking updates on WhatsApp.</p><button className="button outline" type="button" onClick={()=>setSuccess(false)}>Book another appointment</button></motion.div>:
  <motion.form {...reveal} onSubmit={submit} noValidate><div className="form-row">{field('name','Full name *')}{field('phone','Phone number *','tel')}</div><label>Preferred service *<select name="service" defaultValue="" aria-invalid={!!errors.service}><option value="" disabled>Select a service</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select>{errors.service&&<small>{errors.service}</small>}</label><div className="form-row">{field('date','Preferred date *','date')}{field('time','Preferred time *','time')}</div><label>Message (optional)<textarea name="message" rows="3" maxLength="500" placeholder="Anything you’d like the studio to know?"/></label>{errors.form&&<p className="booking-error" role="alert">{errors.form}</p>}<button className="button gold full" type="submit" disabled={busy}>{busy?'Checking availability…':isSupabaseConfigured?'Request appointment':'Prepare WhatsApp request'}<ArrowRight size={17}/></button></motion.form>}
 </div></section>
}
