import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import { ArrowRight, ArrowUp, Camera, Check, ChevronLeft, ChevronRight, MapPin, Menu, MessageCircle, Phone, Star, X } from 'lucide-react';
import { business, features, gallery, mapEmbed, mapsUrl, serviceBookingUrl, services } from './data';
import CustomerBooking from './components/CustomerBooking';

const navItems = ['Home','Services','Gallery','Reviews','Contact'];
const reveal = { initial:{opacity:0,y:28}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.15}, transition:{duration:.65,ease:[.22,1,.36,1]} };
const ext = { target:'_blank', rel:'noopener noreferrer' };

function Stars({ size=18 }) { return <span className="stars" aria-label="5 out of 5 stars">{[0,1,2,3,4].map(i=><Star key={i} size={size} fill="currentColor" aria-hidden="true" />)}</span> }
function Logo(){ return <a href="#home" className="logo" aria-label="I Cut home"><strong>I CUT</strong><span>Hair Grooming Studio</span></a> }
function SectionHead({eyebrow,title,copy,center=false}){return <motion.div {...reveal} className={`section-head ${center?'center':''}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</motion.div>}

function Navigation(){
  const [open,setOpen]=useState(false), [scrolled,setScrolled]=useState(false), [active,setActive]=useState('Home');
  useEffect(()=>{ const onScroll=()=>{setScrolled(scrollY>30); let current='Home'; navItems.forEach(n=>{const el=document.getElementById(n.toLowerCase());if(el&&scrollY>=el.offsetTop-180)current=n});setActive(current)}; onScroll(); addEventListener('scroll',onScroll,{passive:true}); return()=>removeEventListener('scroll',onScroll)},[]);
  useEffect(()=>{document.body.style.overflow=open?'hidden':''; return()=>{document.body.style.overflow=''}},[open]);
  return <header className={`nav ${scrolled||open?'solid':''}`}><div className="nav-inner"><Logo/><nav className="desktop-nav" aria-label="Main navigation">{navItems.map(n=><a className={active===n?'active':''} href={`#${n.toLowerCase()}`} key={n}>{n}</a>)}</nav><a className="button gold desktop-book conversion-link" href={business.bookingUrl}>Book appointment</a><button className="menu-btn" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open?'Close menu':'Open menu'}>{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.nav id="mobile-menu" className="mobile-menu" initial={{opacity:0,y:-18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-18}} aria-label="Mobile navigation">{navItems.map((n,i)=><motion.a initial={{opacity:0,x:-10}} animate={{opacity:1,x:0}} transition={{delay:i*.04}} href={`#${n.toLowerCase()}`} onClick={()=>setOpen(false)} key={n}>{n}</motion.a>)}<a className="button gold conversion-link" href={business.bookingUrl}>Book appointment</a></motion.nav>}</AnimatePresence></header>
}

function Hero(){ const ref=useRef(null);const reduce=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const y=useTransform(scrollYProgress,[0,1],['0%','18%']);return <section id="home" ref={ref} className="hero"><motion.div className="hero-bg" style={{y:reduce?0:y}}/><div className="hero-shade"/><div className="hero-content wrap"><motion.div initial="hidden" animate="show" variants={{hidden:{},show:{transition:{staggerChildren:.12}}}}>{[
  <div className="eyebrow" key="e">PREMIUM GROOMING STUDIO <i/> MUVATTUPUZHA</div>,<h1 key="h">Precision Cuts.<br/><em>Confident Style.</em></h1>,<p key="p">Experience expert haircuts and modern grooming in a studio focused on detail, comfort and your individual style.</p>,<div className="hero-actions" key="a"><a className="button gold conversion-link" href={business.bookingUrl}>Book an appointment <ArrowRight size={17}/></a><a className="button outline conversion-link" href={mapsUrl}><MapPin size={17}/> Get directions</a><a className="text-link" href={business.callUrl}><Phone size={17}/> {business.phone}</a></div>,<div className="hero-rating" key="r"><Stars/><span><b>5.0 rating</b> from 35 happy customers</span></div>
].map((item,i)=><motion.div key={i} variants={{hidden:{opacity:0,y:24},show:{opacity:1,y:0,transition:{duration:.65}}}}>{item}</motion.div>)}</motion.div></div><a href="#about" className="scroll-cue"><span/>Scroll to discover</a></section> }

function Services(){return <section id="services" className="section services"><div className="wrap"><SectionHead eyebrow="THE SERVICES" title="Grooming, Refined" copy="Choose the service that fits your next look. For current pricing and availability, contact the studio directly."/><motion.div className="service-grid" initial="hidden" whileInView="show" viewport={{once:true,amount:.1}} variants={{show:{transition:{staggerChildren:.08}}}}>{services.map((s,i)=><motion.article variants={{hidden:{opacity:0,y:28},show:{opacity:1,y:0}}} className="service-card" key={s.name}><div className="service-number">0{i+1}</div><s.icon className="service-icon"/><h3>{s.name}</h3><p>{s.description}</p><div className="service-bottom"><span>Contact for price</span><a href={serviceBookingUrl(s.name)} className="service-book" aria-label={`Book ${s.name} on WhatsApp`}>Book now <ArrowRight size={15}/></a></div></motion.article>)}</motion.div></div></section>}

function Why(){return <section className="section why"><div className="wrap why-layout"><div><SectionHead eyebrow="WHY I CUT" title="The Detail Makes the Difference"/><div className="why-list">{features.map((f,i)=><motion.div {...reveal} transition={{...reveal.transition,delay:i*.05}} key={f.title}><f.icon/><span>{f.title}</span></motion.div>)}</div></div><motion.div {...reveal} className="stats-panel"><span className="eyebrow">CUSTOMER CONFIDENCE</span><div className="stat"><strong>35</strong><span>customer reviews</span></div><div className="stat"><strong>5.0</strong><span>overall rating</span></div><div className="stat"><strong>100%</strong><span>five-star reviews</span></div></motion.div></div></section>}

function Gallery(){const [selected,setSelected]=useState(null); const close=()=>setSelected(null); const move=(d)=>setSelected(i=>(i+d+gallery.length)%gallery.length); useEffect(()=>{if(selected===null)return;const key=e=>{if(e.key==='Escape')close();if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)};addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',key);document.body.style.overflow=''}},[selected]); return <section id="gallery" className="section gallery-section wrap"><SectionHead eyebrow="THE GALLERY" title="Craft in Every Detail" copy="A glimpse into the craft, atmosphere and modern grooming experience."/><div className="gallery-grid">{gallery.map((g,i)=><motion.button {...reveal} className={`gallery-item item-${i+1}`} key={g.src} onClick={()=>setSelected(i)} aria-label={`Open image: ${g.label}`}><img src={g.src} alt={g.alt} loading="lazy"/><span>{g.label}<ArrowRight/></span></motion.button>)}</div><div className="center-action"><a className="button outline" href={business.instagram} {...ext}><Camera size={18}/> See more on Instagram</a></div><AnimatePresence>{selected!==null&&<motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true" aria-label="Gallery lightbox" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><button className="light-close" onClick={close} aria-label="Close lightbox"><X/></button><button className="light-prev" onClick={()=>move(-1)} aria-label="Previous image"><ChevronLeft/></button><motion.figure key={selected} initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}}><img src={gallery[selected].src} alt={gallery[selected].alt}/><figcaption>{gallery[selected].label} · {selected+1}/{gallery.length}</figcaption></motion.figure><button className="light-next" onClick={()=>move(1)} aria-label="Next image"><ChevronRight/></button></motion.div>}</AnimatePresence></section>}

function Reviews(){return <section id="reviews" className="section reviews"><motion.div {...reveal} className="review-inner wrap"><div><span className="eyebrow">CUSTOMER RATING</span><strong className="rating-big">5.0</strong><Stars size={23}/></div><div className="review-copy"><span className="recommended"><Check size={16}/> Customer Recommended</span><h2>Every review.<br/><em>Every star.</em></h2><p>Based on 35 five-star reviews. A reflection of the care, detail and customer satisfaction at the heart of every visit.</p></div></motion.div></section>}

function Contact(){return <section id="contact" className="section contact wrap"><SectionHead eyebrow="FIND THE STUDIO" title="Visit I Cut" copy="Call or message the salon for today’s availability."/><div className="contact-layout"><motion.div {...reveal} className="contact-card"><h3>{business.name}</h3><p>{business.addressLines[0]}<br/>{business.addressLines[1]}</p><div className="contact-lines"><a href={business.callUrl}><Phone/> <span>Phone<small>{business.phone}</small></span></a><a href={business.instagram} {...ext}><Camera/> <span>Instagram<small>{business.instagramHandle}</small></span></a></div><div className="contact-buttons"><a className="button gold" href={business.callUrl}>Call now</a><a className="button outline" href={business.whatsappBase} {...ext}>WhatsApp</a><a className="button outline" href={mapsUrl} {...ext}>Get directions</a></div></motion.div><motion.div {...reveal} className="map-wrap"><iframe title="Map showing I Cut Hair Grooming Studio in Mudavoor, Muvattupuzha" src={mapEmbed} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></motion.div></div></section>}

function Footer(){return <><footer><div className="wrap footer-grid"><div><Logo/><p>Precision grooming and confident style in the heart of Muvattupuzha.</p></div><div><h4>Explore</h4>{navItems.map(n=><a key={n} href={`#${n.toLowerCase()}`}>{n}</a>)}</div><div><h4>Contact</h4><p>{business.address}</p><a href={business.callUrl}>{business.internationalPhone}</a><a href={business.whatsappBase} {...ext}>WhatsApp</a><a href={business.instagram} {...ext}>Instagram</a><a href={mapsUrl} {...ext}>Directions</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} I Cut Hair Grooming Studio</span><a href="#home">Back to top <ArrowUp size={15}/></a></div></footer><div className="floating"><a href={business.callUrl} aria-label="Call I Cut"><Phone/></a><a href={business.whatsappBase} {...ext} aria-label="Message I Cut on WhatsApp"><MessageCircle/></a><a href={mapsUrl} {...ext} aria-label="Get directions to I Cut"><MapPin/></a></div></>}
export default function App(){return <><Navigation/><main><Hero/><Services/><Why/><Gallery/><Reviews/><CustomerBooking/><Contact/></main><Footer/></>}
